### ISSUE TITLE
how to deploy it for community use

### ISSUE THREAD

**Issue by tvvocold** [sous-chefs/dnsmasq#14]
hello i am a member of fedora chinese community  ,for some reason chinese could't open utube or google,so i wanna build a 'green' dns server like openerdns.(for open google without VPN.)
with the help of http://blog.cnwyhx.com/centos-linux-dnsmasq-install-dns/
i have build dnsmasq in digitalocean (Singapore) and now i wanna it for community use(every one in community could just change their dns to my DO public IP and open google normally.
how could i get it done?

**Comment by qubitrenegade** [comment]
@tvvocold as this is a 4 year old issue, I'm going to hope you found a solution?  Though I believe that this question is really out of the scope of this cookbook.

@sous-chefs can we close this ticket?
