### ISSUE TITLE
Docker requires -u root, ̶ ̶a̶l̶t̶h̶o̶u̶g̶h̶ ̶I̶ ̶a̶m̶ ̶s̶u̶r̶e̶ ̶ ̶y̶o̶u̶ ̶d̶o̶n̶'̶t̶ ̶e̶v̶e̶n̶ ̶c̶a̶r̶e̶ ̶a̶n̶y̶m̶o̶r̶e̶  you care~

### ISSUE THREAD

**Issue by asciifaceman** [sous-chefs/dnsmasq#18]
https://github.com/docker/docker/issues/4366

**Comment by luckymike** [comment]
Sorry? Is there another issue related to this. As far as I can tell, you're the first to report it. We're not heavy Docker users, so we can't be expected to know about every flag that is required to run things properly on a rapidly evolving platform.

We can certainly look into an update for this, but would be even more excited to address it if you could provide a PR.

Thanks for the heads-up.

**Comment by asciifaceman** [comment]
Sooo sorry I was being snarky because I thought this was unmaintained.

The fix is simply 

default['dnsmasq']['dhcp']['user'] = 'root'

**Comment by asciifaceman** [comment]
(You already have the config template dynamic enough to support this)

```
![thefix](https://cloud.githubusercontent.com/assets/1619591/9775510/9c3223a8-5704-11e5-8e48-fcb18b3e49f6.PNG)

Sorry it is an image and not a snippet

**Comment by asciifaceman** [comment]
for posterity, original error.

proposed fix is simply an update to the README.md for config when it concerns docker, and some other flavors of virtualization :)

![originalerror](https://cloud.githubusercontent.com/assets/1619591/9775530/caa1106e-5704-11e5-92fd-637b19a4307b.PNG)

**Comment by asciifaceman** [comment]
https://github.com/hw-cookbooks/dnsmasq/pull/19

**Comment by qubitrenegade** [comment]
Can we close thise?  PR #19 has been merged.
