### ISSUE TITLE
Hosts file not written by default - documentation not clear

### ISSUE THREAD

**Issue by DarrenV79** [sous-chefs/dnsmasq#24]
Hi,

The documentation is not clear that the user should call hosts_file::default recipe after running this to update the hosts file.  Took us a while to work out why our hosts wasn't getting updated.

**Comment by qubitrenegade** [comment]
I believe the [manage_hostsfile](https://github.com/sous-chefs/dnsmasq#manage_hostsfile) documentation resolves this.

Can we close this?
