### ISSUE TITLE
Disabled systemd-resolved breaks cookbook

### ISSUE THREAD

**Issue by ingobecker** [sous-chefs/dnsmasq#35]
Since version 0.3.0 the cookbook fails due to the fact systemd-resolved is disabled which results in the problem, that the dnsmasq package can't be installed because apt can't resolve the package repository URL. I'm converging against Ubuntu 18.04 using chef-client 14.12.9

**Comment by axelrtgs** [comment]
i hit the same issue, it only happens on Ubuntu 18.04.
ubuntu 16.04 and CentOS7 don't suffer this issue.

My question is do we really need to disable the built in systemd-resolved on 18.04?
If its really necessary can we instead install and configure the dnsmasq package, disable and then point dns to localhost so we can keep name resolution?
