### ISSUE TITLE
Provide a data bag example entry

### ISSUE THREAD

**Issue by jbianquetti** [sous-chefs/dnsmasq#4]
would be great if you could add a sample data bag

**Comment by j2ali** [comment]
@ka2er @jbianquetti @mannytoledo 

Your data bag should instead look like this
```
{
  "id": "managed_hosts",
  "maps": {
    "192.168.0.1": "mydomain.com"
  }
}
```

**Comment by qubitrenegade** [comment]
Can we close this?  since #22 is merged?

**Comment by ka2er** [comment]
It seems ok

On 1 May 2019, at 21:23, qubitrenegade <notifications@github.com<mailto:notifications@github.com>> wrote:


Can we close this? since #22<https://github.com/sous-chefs/dnsmasq/pull/22> is merged?
